/twist_mux/add_analyzer_node:
  ros__parameters:
    path: Diagnostics
    navigation:
      type: 'diagnostic_aggregator/AnalyzerGroup'
      path: Navigation
      analyzers:
        twist_mux:
          type: diagnostic_aggregator/GenericAnalyzer
          path: Twist Mux
          find_and_remove_prefix: [ 'twist_mux: ' ]
