# Input topics handled/muxed by the twist mux.
# For each topic:
# - name    : name identifier to select the topic
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

/twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 10
      keyboard:
        topic   : key_vel
        timeout : 0.5
        priority: 90
      rviz:
        topic   : rviz_joy_vel
        timeout : 0.5
        priority: 100
      joystick:
        topic   : joy_vel
        timeout : 0.5
        priority: 100
      webgui_joystick:
        topic   : tab_vel
        timeout : 0.5
        priority: 100
      assisted_teleop:
        topic   : assisted_vel
        timeout : 0.5
        priority: 200
      docking:
        topic   : docking_vel
        timeout : 0.5
        priority: 210