gains:
  torso_lift_joint: {p: 30000,  d: 250, i: 10, i_clamp: 1.5}
  head_1_joint: {p: 100,  d: 0, i: 10, i_clamp: 1.5}
  head_2_joint: {p: 100,  d: 0, i: 10, i_clamp: 1.5}
  xtion_frame_joint: {p: 0.5,  d: 0, i: 0, i_clamp: 1.5}

  arm_1_joint: {p: 3000, d: 5, i: 1,   i_clamp: 3, torque_clamp: 60}
  arm_2_joint: {p: 3000, d: 5, i: 1,   i_clamp: 3, torque_clamp: 50}
  arm_3_joint: {p: 3000, d: 5, i: 1,   i_clamp: 3, torque_clamp: 50}
  arm_4_joint: {p: 3000, d: 5, i: 1,   i_clamp: 3, torque_clamp: 50}
  arm_5_joint: {p: 500,  d: 1, i: 0.1, i_clamp: 3, torque_clamp: 50}
  arm_6_joint: {p: 500,  d: 1, i: 0.1, i_clamp: 3, torque_clamp: 50}
  arm_7_joint: {p: 500,  d: 1, i: 0.1, i_clamp: 3, torque_clamp: 50}

  hand_index_joint: &finger_gains {p: 50,  d: 0.1,  i: 0.1, i_clamp: 1}
  hand_thumb_joint: *finger_gains
  hand_mrl_joint: *finger_gains
  hand_index_abd_joint: *finger_gains
  hand_index_virtual_1_joint: *finger_gains
  hand_index_virtual_2_joint: *finger_gains
  hand_index_virtual_3_joint: *finger_gains
  hand_index_flex_1_joint: *finger_gains
  hand_index_flex_2_joint: *finger_gains
  hand_index_flex_3_joint: *finger_gains
  hand_index_joint: *finger_gains
  hand_little_abd_joint: *finger_gains
  hand_little_virtual_1_joint: *finger_gains
  hand_little_virtual_2_joint: *finger_gains
  hand_little_virtual_3_joint: *finger_gains
  hand_little_flex_1_joint: *finger_gains
  hand_little_flex_2_joint: *finger_gains
  hand_little_flex_3_joint: *finger_gains
  hand_middle_abd_joint: *finger_gains
  hand_middle_virtual_1_joint: *finger_gains
  hand_middle_virtual_2_joint: *finger_gains
  hand_middle_virtual_3_joint: *finger_gains
  hand_middle_flex_1_joint: *finger_gains
  hand_middle_flex_2_joint: *finger_gains
  hand_middle_flex_3_joint: *finger_gains
  hand_ring_abd_joint: *finger_gains
  hand_ring_virtual_1_joint: *finger_gains
  hand_ring_virtual_2_joint: *finger_gains
  hand_ring_virtual_3_joint: *finger_gains
  hand_ring_flex_1_joint: *finger_gains
  hand_ring_flex_2_joint: *finger_gains
  hand_ring_flex_3_joint: *finger_gains
  hand_thumb_abd_joint: *finger_gains
  hand_thumb_virtual_1_joint: *finger_gains
  hand_thumb_virtual_2_joint: *finger_gains
  hand_thumb_virtual_3_joint: *finger_gains
  hand_thumb_flex_1_joint: *finger_gains
  hand_thumb_flex_2_joint: *finger_gains
  hand_thumb_flex_3_joint: *finger_gains
  hand_thumb_joint: *finger_gains
  hand_mrl_joint: *finger_gains

  gripper_left_finger_joint: &gripper_finger_gains {p: 2000,  d: 0,  i: 0, p_gain: 2000}
  gripper_right_finger_joint: *gripper_finger_gains

