/torso_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    # TODO use_sim_time as argument
    use_sim_time: True  # comment when working with the robot
    joints:
      - torso_lift_joint
    command_interfaces:
      - position
    state_interfaces:
      - position

    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 5.0 # FIXME: See #8429
      torso_lift_joint:
        goal: 0.02
